version: '3.9'
services:
  consul:
    image: hashicorp/consul:1.14.5
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:
      - ./consul/data:/consul/data
    command: "agent -dev -client=0.0.0.0"
    network_mode: host

  vault:
    image: hashicorp/vault:1.15.0
    container_name: vault
    ports:
      - "8200:8200"
    network_mode: host
    environment:
      VAULT_ADDR: vault:8200
      VAULT_LOCAL_CONFIG: |
        {
          "backend": {
            "consul": {
              "address": "127.0.0.1:8500",
              "path": "vault/"
            }
          },
          "listener": [{
            "tcp": {
              "address": "0.0.0.0:8200",
              "tls_disable": 1
            }
          }],
          "default_lease_ttl": "168h",
          "max_lease_ttl": "720h",
          "ui": true
        } 
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/file:/vault/file
    command: "server"